### ISSUE TITLE
Please provide MacOSX build instructions.

### ISSUE THREAD

**Issue by CHJ85** [TallenPeli/yuzu-mirror#1]
Hi there. Thanks for creating this mirror.
Now that Yuzu is gone from Homebrew, do you think you could provide build instructions for Mac?
I'm sure they're quite similar to Linux, but I don't wanna make mistakes.
Thanks.

**Comment by TallenPeli** [comment]
I would love to, however I do not personally own a Mac. I'll try my best to figure out a solution
